import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Private file storage. Keys are generated by the server (never from user input)
 * and files are only reachable through the authorized download route.
 */
export interface StorageAdapter {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
}

const KEY_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(pdf|png|jpg)$/;

export function assertSafeKey(key: string): string {
  if (!KEY_RE.test(key)) throw new Error("Invalid storage key");
  return key;
}

/** Local disk adapter. The root must be outside `public/`; resolved paths are confined to it. */
export function localStorageAdapter(root: string): StorageAdapter {
  const base = path.resolve(root, "documents");
  const resolve = (key: string) => {
    const p = path.resolve(base, assertSafeKey(key));
    if (path.dirname(p) !== base) throw new Error("Path traversal blocked");
    return p;
  };
  return {
    async put(key, bytes) {
      await mkdir(base, { recursive: true });
      // "wx": never overwrite an existing object.
      await writeFile(resolve(key), bytes, { flag: "wx", mode: 0o600 });
    },
    async get(key) {
      return readFile(resolve(key));
    },
  };
}

/**
 * S3-compatible adapter placeholder. Wire an S3 client here (private bucket,
 * server-side encryption, no public ACLs) when STORAGE_DRIVER=s3 is used.
 */
export function s3StorageAdapter(): StorageAdapter {
  const fail = async (): Promise<never> => {
    throw new Error("S3 storage is not configured in this deployment.");
  };
  return { put: fail, get: fail };
}

let cached: StorageAdapter | undefined;

export function getStorage(): StorageAdapter {
  if (!cached) {
    cached = process.env.STORAGE_DRIVER === "s3" ? s3StorageAdapter() : localStorageAdapter(process.env.STORAGE_LOCAL_DIR ?? "./.storage");
  }
  return cached;
}

/** For tests: use a specific adapter. */
export function setStorageForTests(adapter: StorageAdapter | undefined) {
  cached = adapter;
}
